FROM node:22-alpine

# Activer corepack pour utiliser pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

# On copie tout le projet directement pour le dev
COPY . .

# Installer les dépendances
RUN pnpm install

# Générer le client Prisma
RUN pnpm --filter @kirenina/api db:generate

# Exposer les ports API et Web
EXPOSE 3001 3000

# Lancer Turborepo en mode dev
CMD ["pnpm", "dev"]
